title: Next year, you're the speaker
email: andrev@fidrildi.com
description: >- # this means to ignore newlines until "baseurl:"
  Materials for the Next year, you're the speaker workshop
author: André Heie Vik
github_username:  andrev
